version: "2"
services:
  arangodb:
    image: arangodb
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: fl01
    command: bash -c "gunicorn --chdir /src/ -w 2 -b 0.0.0.0:8080 recommendations:api"
    depends_on:
      - arangodb
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    links:
      - arangodb
