version: "2"
services:
  arangodb:
    image: arangodb
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=4450c00e19eaa8428464ef3c36cfae5adc3d301e7333d254220eb615cdcb3d7e
    volumes:
      - arangodb:/var/lib/arangodb
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    command: bash -c "gunicorn --chdir /src/ -b 0.0.0.0:8080 main:api"
    depends_on:
      - arangodb
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    links:
      - arangodb
volumes:
  arangodb:
